techapp/urls.py
from django.urls import path
from . import views

app_name = 'techapp'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('search', views.Search, name='search'),
    path('shop_info/<str:restid>', views.ShopInfo, name='shop_info'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
]

techpit/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('techapp.urls')), 
]

techapp/models.py
from django.db import models
from django.contrib.auth.models import User #追加


class Category(models.Model):
    category_l = models.CharField("業態カテゴリ", max_length=10, blank=False)
    name = models.CharField("業態名", max_length=30, blank=False)

    def __str__(self):
        return str(self.name)


class Pref(models.Model):
    pref = models.CharField("都道府県コード", max_length=6, blank=False)
    name = models.CharField("都道府県名", max_length=10, blank=False)

    def __str__(self):
        return str(self.name)


SCORE_CHOICES = [
    (1, '★'),
    (2, '★★'),
    (3, '★★★'),
    (4, '★★★★'),
    (5, '★★★★★'),
]

class Review(models.Model):
    shop_id = models.CharField('店舗ID', max_length=10, blank=False)
    shop_name = models.CharField('店舗名', max_length=200, blank=False)
    image_url = models.CharField('画像１URL', max_length=300, blank=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    comment = models.TextField(verbose_name='レビューコメント', blank=False)
    score = models.PositiveSmallIntegerField(verbose_name='レビュースコア', choices=SCORE_CHOICES, default='3')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('shop_id', 'user')

    def __str__(self):
        return str(self.shop_id)

    def get_percent(self):
        percent = round(self.score / 5 * 100)
        return percent

techapp/forms.py
from django import forms
from .models import Category, Pref, User, Review
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class SearchForm(forms.Form):
    selected_pref = forms.ModelChoiceField(
        label='都道府県',
        required=False,
        queryset=Pref.objects,
    )
    selected_category = forms.ModelChoiceField(
        label='業態',
        required=False,
        queryset=Category.objects,
    )
    freeword = forms.CharField(min_length = 2, max_length = 100, label='', required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        selected_pref = self.fields['selected_pref']
        selected_category = self.fields['selected_category']


# ユーザ登録機能実装時に追加
class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['score', 'comment']

techapp/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, TemplateView
from .models import Pref, Category, Review
from .forms import SearchForm, SignUpForm, LoginForm, ReviewForm
import json
import requests
from django.contrib.auth import login, authenticate
from django.contrib.auth.views import LoginView, LogoutView
from django.db.models import Avg
from django.contrib import messages


# グローバル関数として定義。どこからもkeyidを呼び出すことが出来る。
def get_keyid():
    return "296f76d7037341ade00e99ce1c5da7bb"


class IndexView(TemplateView):
    template_name = 'techapp/index.html'

    def get_context_data(self, *args, **kwargs):
        searchform = SearchForm()
        query = get_gnavi_data("", "RSFST09000", "", "花見", 12)
        res_list = rest_search(query)
        pickup_list = extract_restaurant_info(res_list)
        review_list = Review.objects.all()[:10]

        params = {
            'searchform': searchform,
            'pickup_list': pickup_list,
            'review_list': review_list
            }

        return params


def Search(request):
    if request.method == 'GET':
        searchform = SearchForm(request.POST)

        if searchform.is_valid():
            category_l = request.GET['category_l']
            pref = request.GET['pref']
            freeword = request.GET['freeword']
            query = get_gnavi_data("", category_l, pref, freeword, 10)
            res_list = rest_search(query)
            total_hit_count = len(res_list)
            # 4. 整形した情報をリスト形式で保存し、paramsの一要素として渡す
            restaurants_info = extract_restaurant_info(res_list)

    params = {
        'total_hit_count': total_hit_count,
        'restaurants_info': restaurants_info,
        }

    return render (request, 'techapp/search.html', params)


# 1. 検索条件としてのパラメータを保持するための関数
def get_gnavi_data(id, category_l, pref, freeword, hit_per_page):
    keyid = get_keyid()
    # 一度に取得できる最大件数
    hit_per_page = hit_per_page
    # 店舗のid（グルナビ内で一意になっている）
    id = id
    # 大業態カテゴリ
    category_l = category_l
    #pref
    pref = pref
    #Freeword
    freeword = freeword
    #今回は関東地方のみ（コール回数を少なくするため）
    area = "AREA110"
    #パラメータ設定
    query = {"keyid": keyid, "id":id, "area":area, "pref":pref, "category_l":category_l,"hit_per_page":hit_per_page, "freeword":freeword}

    return query


# 2. 該当の情報を取得するための関数
def rest_search(query):
    res_list = []
    res = json.loads(requests.get("https://api.gnavi.co.jp/RestSearchAPI/v3/", params=query).text)
    # レスポンスがerror でない場合に処理を開始する
    if "error" not in res:
        res_list.extend(res["rest"])
    return res_list


# 3. 取得した情報を整形するための関数
def extract_restaurant_info(restaurants: 'restaurant response') -> 'restaurant list':
    restaurant_list = []
    for restaurant in restaurants:
        id = restaurant["id"]
        name = restaurant["name"]
        name_kana = restaurant["name_kana"]
        url = restaurant["url"]
        url_mobile = restaurant["url_mobile"]
        shop_image1 = restaurant["image_url"]["shop_image1"]
        shop_image2 = restaurant["image_url"]["shop_image2"]
        address = restaurant["address"]
        tel = restaurant["tel"]
        station_line = restaurant["access"]["line"]
        station = restaurant["access"]["station"]
        latitude = restaurant["latitude"]
        longitude = restaurant["longitude"]
        pr_long = restaurant["pr"]["pr_long"]

        restaurant_list.append([id, name, name_kana, url, url_mobile, shop_image1, shop_image2, address, tel, station_line, station, latitude, longitude, pr_long])
    return restaurant_list


def ShopInfo(request, restid):
    keyid = get_keyid()
    id = restid
    query = get_gnavi_data(id, "", "", "", 1)
    res_list = rest_search(query)
    restaurants_info = extract_restaurant_info(res_list)
    review_count = Review.objects.filter(shop_id=restid).count()
    score_ave = Review.objects.filter(shop_id = restid).aggregate(Avg('score'))
    average = score_ave['score__avg']
    if average:
        average_rate = average / 5 * 100
    else:
        average_rate = 0

    if request.method == 'GET':        
        review_form = ReviewForm()
        review_list = Review.objects.filter(shop_id = restid)
    else:
        form = ReviewForm(data=request.POST)
        score = request.POST['score']
        comment = request.POST['comment']

        if form.is_valid():
            review = Review()
            review.shop_id = restid
            review.shop_name = restaurants_info[0][1]
            review.image_url = restaurants_info[0][5]
            review.user = request.user
            review.score = score
            review.comment = comment
            review.save()
            messages.success(request, 'レビューを投稿しました。') # 追加
            return redirect('techapp:shop_info', restid)
        else:
            messages.error(request, 'エラーがあります。') # 追加
            return redirect('techapp:shop_info', restid)
        return render(request, 'techapp/index.html', {})

    params = {
        'title': '店舗詳細',
        'review_count': review_count,
        'restaurants_info': restaurants_info,
        'review_form': review_form,
        'review_list': review_list,
        'average': average,
        'average_rate': average_rate,
        }

    return render (request, 'techapp/shop_info.html', params)


class SignUp(CreateView):
    form_class = SignUpForm
    template_name = 'techapp/signup.html'

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('techapp:index')
        return render(request, 'techapp/signup.html', {'form': form})


class Login(LoginView):
    form_class = LoginForm
    template_name = 'techapp/login.html'


class Logout(LogoutView):
    template_name = 'techapp/logout.html'

techapp/templates/base.html
{% load static %}

<!doctype html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- オリジナルのCSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">
    {% block script%}{% endblock script %}
    {% block css%}{% endblock css %}
    <title>食べナビ</title>
  </head>
  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-right">
        <a class="navbar-brand" href="{% url 'techapp:index' %}">食べナビ</a>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'techapp:index' %}">TOP<span class="sr-only">(current)</span></a>
              </li>
            </ul>

            <ul class="navbar-nav mr-auto">
              {% if user.is_authenticated %}
              <li>
                <a class="nav-item nav-link" href="{% url 'techapp:logout' %}">ログアウト</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-item nav-link" href="{% url 'techapp:login' %}">ログイン</a>
              </li>
              <li>
                <a class="nav-item nav-link" href="{% url 'techapp:signup' %}">新規ユーザ登録</a>
              </li>
              {% endif %}
            </ul>

        <form method="GET" action="{% url 'techapp:search' %}" name="searchform">
                <ul class="navbar-nav mr-auto">  
                  <li class="nav-item">
                    <select class="form-control nav-link" name="pref">
                        <option value="">都道府県</option>
                        {% for item in pref_list %}
                        <option value="{{item.pref}}">{{ item.name }}</option>
                        {% endfor %}
                    </select>
                  </li>
                  <li class="nav-item">
                    <select class="form-control nav-link" name="category_l">
                        <option value="">カテゴリ</option>
                        {% for item in category_list %}
                        <option value="{{item.category_l}}">{{ item.name }}</option>
                        {% endfor %}
                    </select>
                  </li>
                  <li class="nav-item">
                      <input class="form-control nav-link" type="text" placeholder="フリーワード" aria-label="Search" name="freeword">
                  </li>
                  <span>　</span>
                  <li class="nav-item">
                      <button type="submit" class="btn common-btn">Search</button>
                  </li>      
              </ul>
            </form>
        </div>
    </nav>
    <br>
    <!-- メッセージフレームワーク追加　ここから-->
    {% if messages %}
    <div class="container" style="margin-top:1rem;">
        <div class="message">
            {% for message in messages %}
                {% if message.tags == "success" %}
                    <div class="alert alert-success" role="alert">
                {% elif message.tags == "error" %}
                    <div class="alert alert-danger" role="alert">
                {% else %}
                    <div class="alert alert-info" role="alert">
                {% endif %}
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
            {% endfor %}
        </div>
    </div>
    {% endif %}
    <!-- メッセージフレームワーク追加　ここまで-->
    {% block content %}
    {% endblock %}


    <br><br>
    <!-- フッター -->
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <br/><br/>
                <hr/>
                <p>tabenavi</p>
                <a href="https://api.gnavi.co.jp/api/scope/" target="_blank">
                  <img src="https://api.gnavi.co.jp/api/img/credit/api_265_65.gif" width="265" height="65" border="0" alt="グルメ情報検索サイト　ぐるなび">
                </a>
                <br/><br/>  
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>